//* * * * * minute hour day(month) month day(week)
cronConfigs:
  -
    path: "echo 'ojbk' >> cron.text"
    cronTime: "* * * * *"
    cronStdOut: "/Users/ck/Documents/go/src/go-cron/cron4/cron3/res.log"
